/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedSuperAdminRouteImport } from './routes/_authenticated/super-admin'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardAnalyticsRouteImport } from './routes/_authenticated/dashboard.analytics'
import { Route as AuthenticatedDashboardAssistantRouteImport } from './routes/_authenticated/dashboard.assistant'
import { Route as AuthenticatedDashboardConversationsRouteImport } from './routes/_authenticated/dashboard.conversations'
import { Route as AuthenticatedDashboardCrmBuilderRouteImport } from './routes/_authenticated/dashboard.crm-builder'
import { Route as AuthenticatedDashboardCustomersRouteImport } from './routes/_authenticated/dashboard.customers'
import { Route as AuthenticatedDashboardInventoryRouteImport } from './routes/_authenticated/dashboard.inventory'
import { Route as AuthenticatedDashboardLeadsRouteImport } from './routes/_authenticated/dashboard.leads'
import { Route as AuthenticatedDashboardOperatorsRouteImport } from './routes/_authenticated/dashboard.operators'
import { Route as AuthenticatedDashboardOrdersRouteImport } from './routes/_authenticated/dashboard.orders'
import { Route as AuthenticatedDashboardPaymentsRouteImport } from './routes/_authenticated/dashboard.payments'
import { Route as AuthenticatedDashboardPipelineRouteImport } from './routes/_authenticated/dashboard.pipeline'
import { Route as AuthenticatedDashboardProductsRouteImport } from './routes/_authenticated/dashboard.products'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardTasksRouteImport } from './routes/_authenticated/dashboard.tasks'
import { Route as AuthenticatedDashboardTelegramRouteImport } from './routes/_authenticated/dashboard.telegram'
import { Route as AuthenticatedSuperAdminIndexRouteImport } from './routes/_authenticated/super-admin.index'
import { Route as AuthenticatedSuperAdminAiUsageRouteImport } from './routes/_authenticated/super-admin.ai-usage'
import { Route as AuthenticatedSuperAdminAnalyticsRouteImport } from './routes/_authenticated/super-admin.analytics'
import { Route as AuthenticatedSuperAdminAuditRouteImport } from './routes/_authenticated/super-admin.audit'
import { Route as AuthenticatedSuperAdminFlagsRouteImport } from './routes/_authenticated/super-admin.flags'
import { Route as AuthenticatedSuperAdminIndustriesRouteImport } from './routes/_authenticated/super-admin.industries'
import { Route as AuthenticatedSuperAdminNotificationsRouteImport } from './routes/_authenticated/super-admin.notifications'
import { Route as AuthenticatedSuperAdminSecurityRouteImport } from './routes/_authenticated/super-admin.security'
import { Route as AuthenticatedSuperAdminSettingsRouteImport } from './routes/_authenticated/super-admin.settings'
import { Route as AuthenticatedSuperAdminUsersRouteImport } from './routes/_authenticated/super-admin.users'
import { Route as AuthenticatedDashboardCrmModuleKeyRouteImport } from './routes/_authenticated/dashboard.crm.$moduleKey'
import { Route as AuthenticatedDashboardCustomersIndexRouteImport } from './routes/_authenticated/dashboard.customers.index'
import { Route as AuthenticatedDashboardCustomersIdRouteImport } from './routes/_authenticated/dashboard.customers.$id'
import { Route as AuthenticatedSuperAdminOrganizationsIndexRouteImport } from './routes/_authenticated/super-admin.organizations.index'
import { Route as AuthenticatedSuperAdminOrganizationsIdRouteImport } from './routes/_authenticated/super-admin.organizations.$id'
import { Route as ApiPublicInstagramWebhookRouteImport } from './routes/api/public/instagram/webhook'
import { Route as ApiPublicTelegramDailyReportRouteImport } from './routes/api/public/telegram/daily-report'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuperAdminRoute = AuthenticatedSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAnalyticsRoute =
  AuthenticatedDashboardAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAssistantRoute =
  AuthenticatedDashboardAssistantRouteImport.update({
    id: '/assistant',
    path: '/assistant',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardConversationsRoute =
  AuthenticatedDashboardConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCrmBuilderRoute =
  AuthenticatedDashboardCrmBuilderRouteImport.update({
    id: '/crm-builder',
    path: '/crm-builder',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCustomersRoute =
  AuthenticatedDashboardCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardInventoryRoute =
  AuthenticatedDashboardInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLeadsRoute =
  AuthenticatedDashboardLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOperatorsRoute =
  AuthenticatedDashboardOperatorsRouteImport.update({
    id: '/operators',
    path: '/operators',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOrdersRoute =
  AuthenticatedDashboardOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPaymentsRoute =
  AuthenticatedDashboardPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPipelineRoute =
  AuthenticatedDashboardPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProductsRoute =
  AuthenticatedDashboardProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTasksRoute =
  AuthenticatedDashboardTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTelegramRoute =
  AuthenticatedDashboardTelegramRouteImport.update({
    id: '/telegram',
    path: '/telegram',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedSuperAdminIndexRoute =
  AuthenticatedSuperAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminAiUsageRoute =
  AuthenticatedSuperAdminAiUsageRouteImport.update({
    id: '/ai-usage',
    path: '/ai-usage',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminAnalyticsRoute =
  AuthenticatedSuperAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminAuditRoute =
  AuthenticatedSuperAdminAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminFlagsRoute =
  AuthenticatedSuperAdminFlagsRouteImport.update({
    id: '/flags',
    path: '/flags',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminIndustriesRoute =
  AuthenticatedSuperAdminIndustriesRouteImport.update({
    id: '/industries',
    path: '/industries',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminNotificationsRoute =
  AuthenticatedSuperAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminSecurityRoute =
  AuthenticatedSuperAdminSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminSettingsRoute =
  AuthenticatedSuperAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminUsersRoute =
  AuthenticatedSuperAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedDashboardCrmModuleKeyRoute =
  AuthenticatedDashboardCrmModuleKeyRouteImport.update({
    id: '/crm/$moduleKey',
    path: '/crm/$moduleKey',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCustomersIndexRoute =
  AuthenticatedDashboardCustomersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardCustomersRoute,
  } as any)
const AuthenticatedDashboardCustomersIdRoute =
  AuthenticatedDashboardCustomersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDashboardCustomersRoute,
  } as any)
const AuthenticatedSuperAdminOrganizationsIndexRoute =
  AuthenticatedSuperAdminOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminOrganizationsIdRoute =
  AuthenticatedSuperAdminOrganizationsIdRouteImport.update({
    id: '/organizations/$id',
    path: '/organizations/$id',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const ApiPublicInstagramWebhookRoute =
  ApiPublicInstagramWebhookRouteImport.update({
    id: '/api/public/instagram/webhook',
    path: '/api/public/instagram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramDailyReportRoute =
  ApiPublicTelegramDailyReportRouteImport.update({
    id: '/api/public/telegram/daily-report',
    path: '/api/public/telegram/daily-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/super-admin': typeof AuthenticatedSuperAdminRouteWithChildren
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/assistant': typeof AuthenticatedDashboardAssistantRoute
  '/dashboard/conversations': typeof AuthenticatedDashboardConversationsRoute
  '/dashboard/crm-builder': typeof AuthenticatedDashboardCrmBuilderRoute
  '/dashboard/customers': typeof AuthenticatedDashboardCustomersRouteWithChildren
  '/dashboard/inventory': typeof AuthenticatedDashboardInventoryRoute
  '/dashboard/leads': typeof AuthenticatedDashboardLeadsRoute
  '/dashboard/operators': typeof AuthenticatedDashboardOperatorsRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/dashboard/payments': typeof AuthenticatedDashboardPaymentsRoute
  '/dashboard/pipeline': typeof AuthenticatedDashboardPipelineRoute
  '/dashboard/products': typeof AuthenticatedDashboardProductsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/tasks': typeof AuthenticatedDashboardTasksRoute
  '/dashboard/telegram': typeof AuthenticatedDashboardTelegramRoute
  '/super-admin/ai-usage': typeof AuthenticatedSuperAdminAiUsageRoute
  '/super-admin/analytics': typeof AuthenticatedSuperAdminAnalyticsRoute
  '/super-admin/audit': typeof AuthenticatedSuperAdminAuditRoute
  '/super-admin/flags': typeof AuthenticatedSuperAdminFlagsRoute
  '/super-admin/industries': typeof AuthenticatedSuperAdminIndustriesRoute
  '/super-admin/notifications': typeof AuthenticatedSuperAdminNotificationsRoute
  '/super-admin/security': typeof AuthenticatedSuperAdminSecurityRoute
  '/super-admin/settings': typeof AuthenticatedSuperAdminSettingsRoute
  '/super-admin/users': typeof AuthenticatedSuperAdminUsersRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
  '/dashboard/crm/$moduleKey': typeof AuthenticatedDashboardCrmModuleKeyRoute
  '/dashboard/customers/$id': typeof AuthenticatedDashboardCustomersIdRoute
  '/super-admin/organizations/$id': typeof AuthenticatedSuperAdminOrganizationsIdRoute
  '/api/public/instagram/webhook': typeof ApiPublicInstagramWebhookRoute
  '/api/public/telegram/daily-report': typeof ApiPublicTelegramDailyReportRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/dashboard/customers/': typeof AuthenticatedDashboardCustomersIndexRoute
  '/super-admin/organizations/': typeof AuthenticatedSuperAdminOrganizationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/assistant': typeof AuthenticatedDashboardAssistantRoute
  '/dashboard/conversations': typeof AuthenticatedDashboardConversationsRoute
  '/dashboard/crm-builder': typeof AuthenticatedDashboardCrmBuilderRoute
  '/dashboard/inventory': typeof AuthenticatedDashboardInventoryRoute
  '/dashboard/leads': typeof AuthenticatedDashboardLeadsRoute
  '/dashboard/operators': typeof AuthenticatedDashboardOperatorsRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/dashboard/payments': typeof AuthenticatedDashboardPaymentsRoute
  '/dashboard/pipeline': typeof AuthenticatedDashboardPipelineRoute
  '/dashboard/products': typeof AuthenticatedDashboardProductsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/tasks': typeof AuthenticatedDashboardTasksRoute
  '/dashboard/telegram': typeof AuthenticatedDashboardTelegramRoute
  '/super-admin/ai-usage': typeof AuthenticatedSuperAdminAiUsageRoute
  '/super-admin/analytics': typeof AuthenticatedSuperAdminAnalyticsRoute
  '/super-admin/audit': typeof AuthenticatedSuperAdminAuditRoute
  '/super-admin/flags': typeof AuthenticatedSuperAdminFlagsRoute
  '/super-admin/industries': typeof AuthenticatedSuperAdminIndustriesRoute
  '/super-admin/notifications': typeof AuthenticatedSuperAdminNotificationsRoute
  '/super-admin/security': typeof AuthenticatedSuperAdminSecurityRoute
  '/super-admin/settings': typeof AuthenticatedSuperAdminSettingsRoute
  '/super-admin/users': typeof AuthenticatedSuperAdminUsersRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/super-admin': typeof AuthenticatedSuperAdminIndexRoute
  '/dashboard/crm/$moduleKey': typeof AuthenticatedDashboardCrmModuleKeyRoute
  '/dashboard/customers/$id': typeof AuthenticatedDashboardCustomersIdRoute
  '/super-admin/organizations/$id': typeof AuthenticatedSuperAdminOrganizationsIdRoute
  '/api/public/instagram/webhook': typeof ApiPublicInstagramWebhookRoute
  '/api/public/telegram/daily-report': typeof ApiPublicTelegramDailyReportRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/dashboard/customers': typeof AuthenticatedDashboardCustomersIndexRoute
  '/super-admin/organizations': typeof AuthenticatedSuperAdminOrganizationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/super-admin': typeof AuthenticatedSuperAdminRouteWithChildren
  '/_authenticated/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/_authenticated/dashboard/assistant': typeof AuthenticatedDashboardAssistantRoute
  '/_authenticated/dashboard/conversations': typeof AuthenticatedDashboardConversationsRoute
  '/_authenticated/dashboard/crm-builder': typeof AuthenticatedDashboardCrmBuilderRoute
  '/_authenticated/dashboard/customers': typeof AuthenticatedDashboardCustomersRouteWithChildren
  '/_authenticated/dashboard/inventory': typeof AuthenticatedDashboardInventoryRoute
  '/_authenticated/dashboard/leads': typeof AuthenticatedDashboardLeadsRoute
  '/_authenticated/dashboard/operators': typeof AuthenticatedDashboardOperatorsRoute
  '/_authenticated/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/_authenticated/dashboard/payments': typeof AuthenticatedDashboardPaymentsRoute
  '/_authenticated/dashboard/pipeline': typeof AuthenticatedDashboardPipelineRoute
  '/_authenticated/dashboard/products': typeof AuthenticatedDashboardProductsRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/tasks': typeof AuthenticatedDashboardTasksRoute
  '/_authenticated/dashboard/telegram': typeof AuthenticatedDashboardTelegramRoute
  '/_authenticated/super-admin/ai-usage': typeof AuthenticatedSuperAdminAiUsageRoute
  '/_authenticated/super-admin/analytics': typeof AuthenticatedSuperAdminAnalyticsRoute
  '/_authenticated/super-admin/audit': typeof AuthenticatedSuperAdminAuditRoute
  '/_authenticated/super-admin/flags': typeof AuthenticatedSuperAdminFlagsRoute
  '/_authenticated/super-admin/industries': typeof AuthenticatedSuperAdminIndustriesRoute
  '/_authenticated/super-admin/notifications': typeof AuthenticatedSuperAdminNotificationsRoute
  '/_authenticated/super-admin/security': typeof AuthenticatedSuperAdminSecurityRoute
  '/_authenticated/super-admin/settings': typeof AuthenticatedSuperAdminSettingsRoute
  '/_authenticated/super-admin/users': typeof AuthenticatedSuperAdminUsersRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
  '/_authenticated/dashboard/crm/$moduleKey': typeof AuthenticatedDashboardCrmModuleKeyRoute
  '/_authenticated/dashboard/customers/$id': typeof AuthenticatedDashboardCustomersIdRoute
  '/_authenticated/super-admin/organizations/$id': typeof AuthenticatedSuperAdminOrganizationsIdRoute
  '/api/public/instagram/webhook': typeof ApiPublicInstagramWebhookRoute
  '/api/public/telegram/daily-report': typeof ApiPublicTelegramDailyReportRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/_authenticated/dashboard/customers/': typeof AuthenticatedDashboardCustomersIndexRoute
  '/_authenticated/super-admin/organizations/': typeof AuthenticatedSuperAdminOrganizationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/super-admin'
    | '/dashboard/analytics'
    | '/dashboard/assistant'
    | '/dashboard/conversations'
    | '/dashboard/crm-builder'
    | '/dashboard/customers'
    | '/dashboard/inventory'
    | '/dashboard/leads'
    | '/dashboard/operators'
    | '/dashboard/orders'
    | '/dashboard/payments'
    | '/dashboard/pipeline'
    | '/dashboard/products'
    | '/dashboard/settings'
    | '/dashboard/tasks'
    | '/dashboard/telegram'
    | '/super-admin/ai-usage'
    | '/super-admin/analytics'
    | '/super-admin/audit'
    | '/super-admin/flags'
    | '/super-admin/industries'
    | '/super-admin/notifications'
    | '/super-admin/security'
    | '/super-admin/settings'
    | '/super-admin/users'
    | '/dashboard/'
    | '/super-admin/'
    | '/dashboard/crm/$moduleKey'
    | '/dashboard/customers/$id'
    | '/super-admin/organizations/$id'
    | '/api/public/instagram/webhook'
    | '/api/public/telegram/daily-report'
    | '/api/public/telegram/webhook'
    | '/dashboard/customers/'
    | '/super-admin/organizations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/dashboard/analytics'
    | '/dashboard/assistant'
    | '/dashboard/conversations'
    | '/dashboard/crm-builder'
    | '/dashboard/inventory'
    | '/dashboard/leads'
    | '/dashboard/operators'
    | '/dashboard/orders'
    | '/dashboard/payments'
    | '/dashboard/pipeline'
    | '/dashboard/products'
    | '/dashboard/settings'
    | '/dashboard/tasks'
    | '/dashboard/telegram'
    | '/super-admin/ai-usage'
    | '/super-admin/analytics'
    | '/super-admin/audit'
    | '/super-admin/flags'
    | '/super-admin/industries'
    | '/super-admin/notifications'
    | '/super-admin/security'
    | '/super-admin/settings'
    | '/super-admin/users'
    | '/dashboard'
    | '/super-admin'
    | '/dashboard/crm/$moduleKey'
    | '/dashboard/customers/$id'
    | '/super-admin/organizations/$id'
    | '/api/public/instagram/webhook'
    | '/api/public/telegram/daily-report'
    | '/api/public/telegram/webhook'
    | '/dashboard/customers'
    | '/super-admin/organizations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/super-admin'
    | '/_authenticated/dashboard/analytics'
    | '/_authenticated/dashboard/assistant'
    | '/_authenticated/dashboard/conversations'
    | '/_authenticated/dashboard/crm-builder'
    | '/_authenticated/dashboard/customers'
    | '/_authenticated/dashboard/inventory'
    | '/_authenticated/dashboard/leads'
    | '/_authenticated/dashboard/operators'
    | '/_authenticated/dashboard/orders'
    | '/_authenticated/dashboard/payments'
    | '/_authenticated/dashboard/pipeline'
    | '/_authenticated/dashboard/products'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/tasks'
    | '/_authenticated/dashboard/telegram'
    | '/_authenticated/super-admin/ai-usage'
    | '/_authenticated/super-admin/analytics'
    | '/_authenticated/super-admin/audit'
    | '/_authenticated/super-admin/flags'
    | '/_authenticated/super-admin/industries'
    | '/_authenticated/super-admin/notifications'
    | '/_authenticated/super-admin/security'
    | '/_authenticated/super-admin/settings'
    | '/_authenticated/super-admin/users'
    | '/_authenticated/dashboard/'
    | '/_authenticated/super-admin/'
    | '/_authenticated/dashboard/crm/$moduleKey'
    | '/_authenticated/dashboard/customers/$id'
    | '/_authenticated/super-admin/organizations/$id'
    | '/api/public/instagram/webhook'
    | '/api/public/telegram/daily-report'
    | '/api/public/telegram/webhook'
    | '/_authenticated/dashboard/customers/'
    | '/_authenticated/super-admin/organizations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicInstagramWebhookRoute: typeof ApiPublicInstagramWebhookRoute
  ApiPublicTelegramDailyReportRoute: typeof ApiPublicTelegramDailyReportRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin': {
      id: '/_authenticated/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthenticatedSuperAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/analytics': {
      id: '/_authenticated/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof AuthenticatedDashboardAnalyticsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/assistant': {
      id: '/_authenticated/dashboard/assistant'
      path: '/assistant'
      fullPath: '/dashboard/assistant'
      preLoaderRoute: typeof AuthenticatedDashboardAssistantRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/conversations': {
      id: '/_authenticated/dashboard/conversations'
      path: '/conversations'
      fullPath: '/dashboard/conversations'
      preLoaderRoute: typeof AuthenticatedDashboardConversationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/crm-builder': {
      id: '/_authenticated/dashboard/crm-builder'
      path: '/crm-builder'
      fullPath: '/dashboard/crm-builder'
      preLoaderRoute: typeof AuthenticatedDashboardCrmBuilderRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/customers': {
      id: '/_authenticated/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof AuthenticatedDashboardCustomersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/inventory': {
      id: '/_authenticated/dashboard/inventory'
      path: '/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof AuthenticatedDashboardInventoryRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/leads': {
      id: '/_authenticated/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof AuthenticatedDashboardLeadsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/operators': {
      id: '/_authenticated/dashboard/operators'
      path: '/operators'
      fullPath: '/dashboard/operators'
      preLoaderRoute: typeof AuthenticatedDashboardOperatorsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/orders': {
      id: '/_authenticated/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof AuthenticatedDashboardOrdersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/payments': {
      id: '/_authenticated/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof AuthenticatedDashboardPaymentsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/pipeline': {
      id: '/_authenticated/dashboard/pipeline'
      path: '/pipeline'
      fullPath: '/dashboard/pipeline'
      preLoaderRoute: typeof AuthenticatedDashboardPipelineRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/products': {
      id: '/_authenticated/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof AuthenticatedDashboardProductsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/tasks': {
      id: '/_authenticated/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof AuthenticatedDashboardTasksRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/telegram': {
      id: '/_authenticated/dashboard/telegram'
      path: '/telegram'
      fullPath: '/dashboard/telegram'
      preLoaderRoute: typeof AuthenticatedDashboardTelegramRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/super-admin/': {
      id: '/_authenticated/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof AuthenticatedSuperAdminIndexRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/ai-usage': {
      id: '/_authenticated/super-admin/ai-usage'
      path: '/ai-usage'
      fullPath: '/super-admin/ai-usage'
      preLoaderRoute: typeof AuthenticatedSuperAdminAiUsageRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/analytics': {
      id: '/_authenticated/super-admin/analytics'
      path: '/analytics'
      fullPath: '/super-admin/analytics'
      preLoaderRoute: typeof AuthenticatedSuperAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/audit': {
      id: '/_authenticated/super-admin/audit'
      path: '/audit'
      fullPath: '/super-admin/audit'
      preLoaderRoute: typeof AuthenticatedSuperAdminAuditRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/flags': {
      id: '/_authenticated/super-admin/flags'
      path: '/flags'
      fullPath: '/super-admin/flags'
      preLoaderRoute: typeof AuthenticatedSuperAdminFlagsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/industries': {
      id: '/_authenticated/super-admin/industries'
      path: '/industries'
      fullPath: '/super-admin/industries'
      preLoaderRoute: typeof AuthenticatedSuperAdminIndustriesRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/notifications': {
      id: '/_authenticated/super-admin/notifications'
      path: '/notifications'
      fullPath: '/super-admin/notifications'
      preLoaderRoute: typeof AuthenticatedSuperAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/security': {
      id: '/_authenticated/super-admin/security'
      path: '/security'
      fullPath: '/super-admin/security'
      preLoaderRoute: typeof AuthenticatedSuperAdminSecurityRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/settings': {
      id: '/_authenticated/super-admin/settings'
      path: '/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof AuthenticatedSuperAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/users': {
      id: '/_authenticated/super-admin/users'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof AuthenticatedSuperAdminUsersRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/dashboard/crm/$moduleKey': {
      id: '/_authenticated/dashboard/crm/$moduleKey'
      path: '/crm/$moduleKey'
      fullPath: '/dashboard/crm/$moduleKey'
      preLoaderRoute: typeof AuthenticatedDashboardCrmModuleKeyRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/customers/': {
      id: '/_authenticated/dashboard/customers/'
      path: '/'
      fullPath: '/dashboard/customers/'
      preLoaderRoute: typeof AuthenticatedDashboardCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardCustomersRoute
    }
    '/_authenticated/dashboard/customers/$id': {
      id: '/_authenticated/dashboard/customers/$id'
      path: '/$id'
      fullPath: '/dashboard/customers/$id'
      preLoaderRoute: typeof AuthenticatedDashboardCustomersIdRouteImport
      parentRoute: typeof AuthenticatedDashboardCustomersRoute
    }
    '/_authenticated/super-admin/organizations/': {
      id: '/_authenticated/super-admin/organizations/'
      path: '/organizations'
      fullPath: '/super-admin/organizations/'
      preLoaderRoute: typeof AuthenticatedSuperAdminOrganizationsIndexRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/organizations/$id': {
      id: '/_authenticated/super-admin/organizations/$id'
      path: '/organizations/$id'
      fullPath: '/super-admin/organizations/$id'
      preLoaderRoute: typeof AuthenticatedSuperAdminOrganizationsIdRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/api/public/instagram/webhook': {
      id: '/api/public/instagram/webhook'
      path: '/api/public/instagram/webhook'
      fullPath: '/api/public/instagram/webhook'
      preLoaderRoute: typeof ApiPublicInstagramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/daily-report': {
      id: '/api/public/telegram/daily-report'
      path: '/api/public/telegram/daily-report'
      fullPath: '/api/public/telegram/daily-report'
      preLoaderRoute: typeof ApiPublicTelegramDailyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDashboardCustomersRouteChildren {
  AuthenticatedDashboardCustomersIdRoute: typeof AuthenticatedDashboardCustomersIdRoute
  AuthenticatedDashboardCustomersIndexRoute: typeof AuthenticatedDashboardCustomersIndexRoute
}

const AuthenticatedDashboardCustomersRouteChildren: AuthenticatedDashboardCustomersRouteChildren =
  {
    AuthenticatedDashboardCustomersIdRoute:
      AuthenticatedDashboardCustomersIdRoute,
    AuthenticatedDashboardCustomersIndexRoute:
      AuthenticatedDashboardCustomersIndexRoute,
  }

const AuthenticatedDashboardCustomersRouteWithChildren =
  AuthenticatedDashboardCustomersRoute._addFileChildren(
    AuthenticatedDashboardCustomersRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAnalyticsRoute: typeof AuthenticatedDashboardAnalyticsRoute
  AuthenticatedDashboardAssistantRoute: typeof AuthenticatedDashboardAssistantRoute
  AuthenticatedDashboardConversationsRoute: typeof AuthenticatedDashboardConversationsRoute
  AuthenticatedDashboardCrmBuilderRoute: typeof AuthenticatedDashboardCrmBuilderRoute
  AuthenticatedDashboardCustomersRoute: typeof AuthenticatedDashboardCustomersRouteWithChildren
  AuthenticatedDashboardInventoryRoute: typeof AuthenticatedDashboardInventoryRoute
  AuthenticatedDashboardLeadsRoute: typeof AuthenticatedDashboardLeadsRoute
  AuthenticatedDashboardOperatorsRoute: typeof AuthenticatedDashboardOperatorsRoute
  AuthenticatedDashboardOrdersRoute: typeof AuthenticatedDashboardOrdersRoute
  AuthenticatedDashboardPaymentsRoute: typeof AuthenticatedDashboardPaymentsRoute
  AuthenticatedDashboardPipelineRoute: typeof AuthenticatedDashboardPipelineRoute
  AuthenticatedDashboardProductsRoute: typeof AuthenticatedDashboardProductsRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardTasksRoute: typeof AuthenticatedDashboardTasksRoute
  AuthenticatedDashboardTelegramRoute: typeof AuthenticatedDashboardTelegramRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardCrmModuleKeyRoute: typeof AuthenticatedDashboardCrmModuleKeyRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAnalyticsRoute: AuthenticatedDashboardAnalyticsRoute,
    AuthenticatedDashboardAssistantRoute: AuthenticatedDashboardAssistantRoute,
    AuthenticatedDashboardConversationsRoute:
      AuthenticatedDashboardConversationsRoute,
    AuthenticatedDashboardCrmBuilderRoute:
      AuthenticatedDashboardCrmBuilderRoute,
    AuthenticatedDashboardCustomersRoute:
      AuthenticatedDashboardCustomersRouteWithChildren,
    AuthenticatedDashboardInventoryRoute: AuthenticatedDashboardInventoryRoute,
    AuthenticatedDashboardLeadsRoute: AuthenticatedDashboardLeadsRoute,
    AuthenticatedDashboardOperatorsRoute: AuthenticatedDashboardOperatorsRoute,
    AuthenticatedDashboardOrdersRoute: AuthenticatedDashboardOrdersRoute,
    AuthenticatedDashboardPaymentsRoute: AuthenticatedDashboardPaymentsRoute,
    AuthenticatedDashboardPipelineRoute: AuthenticatedDashboardPipelineRoute,
    AuthenticatedDashboardProductsRoute: AuthenticatedDashboardProductsRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardTasksRoute: AuthenticatedDashboardTasksRoute,
    AuthenticatedDashboardTelegramRoute: AuthenticatedDashboardTelegramRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardCrmModuleKeyRoute:
      AuthenticatedDashboardCrmModuleKeyRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedSuperAdminRouteChildren {
  AuthenticatedSuperAdminAiUsageRoute: typeof AuthenticatedSuperAdminAiUsageRoute
  AuthenticatedSuperAdminAnalyticsRoute: typeof AuthenticatedSuperAdminAnalyticsRoute
  AuthenticatedSuperAdminAuditRoute: typeof AuthenticatedSuperAdminAuditRoute
  AuthenticatedSuperAdminFlagsRoute: typeof AuthenticatedSuperAdminFlagsRoute
  AuthenticatedSuperAdminIndustriesRoute: typeof AuthenticatedSuperAdminIndustriesRoute
  AuthenticatedSuperAdminNotificationsRoute: typeof AuthenticatedSuperAdminNotificationsRoute
  AuthenticatedSuperAdminSecurityRoute: typeof AuthenticatedSuperAdminSecurityRoute
  AuthenticatedSuperAdminSettingsRoute: typeof AuthenticatedSuperAdminSettingsRoute
  AuthenticatedSuperAdminUsersRoute: typeof AuthenticatedSuperAdminUsersRoute
  AuthenticatedSuperAdminIndexRoute: typeof AuthenticatedSuperAdminIndexRoute
  AuthenticatedSuperAdminOrganizationsIdRoute: typeof AuthenticatedSuperAdminOrganizationsIdRoute
  AuthenticatedSuperAdminOrganizationsIndexRoute: typeof AuthenticatedSuperAdminOrganizationsIndexRoute
}

const AuthenticatedSuperAdminRouteChildren: AuthenticatedSuperAdminRouteChildren =
  {
    AuthenticatedSuperAdminAiUsageRoute: AuthenticatedSuperAdminAiUsageRoute,
    AuthenticatedSuperAdminAnalyticsRoute:
      AuthenticatedSuperAdminAnalyticsRoute,
    AuthenticatedSuperAdminAuditRoute: AuthenticatedSuperAdminAuditRoute,
    AuthenticatedSuperAdminFlagsRoute: AuthenticatedSuperAdminFlagsRoute,
    AuthenticatedSuperAdminIndustriesRoute:
      AuthenticatedSuperAdminIndustriesRoute,
    AuthenticatedSuperAdminNotificationsRoute:
      AuthenticatedSuperAdminNotificationsRoute,
    AuthenticatedSuperAdminSecurityRoute: AuthenticatedSuperAdminSecurityRoute,
    AuthenticatedSuperAdminSettingsRoute: AuthenticatedSuperAdminSettingsRoute,
    AuthenticatedSuperAdminUsersRoute: AuthenticatedSuperAdminUsersRoute,
    AuthenticatedSuperAdminIndexRoute: AuthenticatedSuperAdminIndexRoute,
    AuthenticatedSuperAdminOrganizationsIdRoute:
      AuthenticatedSuperAdminOrganizationsIdRoute,
    AuthenticatedSuperAdminOrganizationsIndexRoute:
      AuthenticatedSuperAdminOrganizationsIndexRoute,
  }

const AuthenticatedSuperAdminRouteWithChildren =
  AuthenticatedSuperAdminRoute._addFileChildren(
    AuthenticatedSuperAdminRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSuperAdminRoute: typeof AuthenticatedSuperAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSuperAdminRoute: AuthenticatedSuperAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicInstagramWebhookRoute: ApiPublicInstagramWebhookRoute,
  ApiPublicTelegramDailyReportRoute: ApiPublicTelegramDailyReportRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
